# Generated by Django 5.1.3 on 2025-05-28 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("price", models.PositiveIntegerField(verbose_name="가격")),
                ("description", models.TextField(verbose_name="설명")),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("NEW", "새 제품"),
                            ("LIKE_NEW", "거의 새 제품"),
                            ("GOOD", "좋음"),
                            ("FAIR", "보통"),
                            ("POOR", "나쁨"),
                        ],
                        max_length=10,
                        verbose_name="상태",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "판매중"),
                            ("RESERVED", "예약중"),
                            ("SOLD", "판매완료"),
                        ],
                        default="AVAILABLE",
                        max_length=10,
                        verbose_name="판매상태",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GUITAR", "기타"),
                            ("BASS", "베이스"),
                            ("DRUM", "드럼"),
                            ("KEYBOARD", "키보드"),
                            ("WIND", "관악기"),
                            ("STRING", "현악기"),
                            ("PERCUSSION", "타악기"),
                            ("AMPLIFIER", "앰프"),
                            ("EFFECT", "이펙터"),
                            ("ACCESSORY", "악세서리"),
                            ("ETC", "기타"),
                        ],
                        max_length=10,
                        verbose_name="카테고리",
                    ),
                ),
                ("brand", models.CharField(max_length=100, verbose_name="브랜드")),
                ("model_name", models.CharField(max_length=100, verbose_name="모델명")),
                (
                    "views",
                    models.PositiveIntegerField(default=0, verbose_name="조회수"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="판매자",
                    ),
                ),
            ],
            options={
                "verbose_name": "상품",
                "verbose_name_plural": "상품 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/%Y/%m/%d/", verbose_name="이미지"
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="대표 이미지"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                        verbose_name="상품",
                    ),
                ),
            ],
            options={
                "verbose_name": "상품 이미지",
                "verbose_name_plural": "상품 이미지 목록",
                "ordering": ["-is_main", "-created_at"],
            },
        ),
    ]
